import random
from datetime import timedelta
from django.core.management.base import BaseCommand
from django.utils import timezone
from books.models import Genre, Book
from events.models import Event


GENRES_AND_BOOKS = {
    'Fiction': [
        ('To Kill a Mockingbird', 'Harper Lee', 1960, 'A gripping tale of racial injustice and moral growth in the American South through the eyes of young Scout Finch.'),
        ('1984', 'George Orwell', 1949, 'A dystopian social science fiction novel set in a totalitarian society under constant government surveillance.'),
        ('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'A portrait of the Jazz Age in all of its decadence and excess, exploring the American Dream.'),
        ('Pride and Prejudice', 'Jane Austen', 1813, 'A romantic novel that charts the emotional development of Elizabeth Bennet in Georgian rural England.'),
        ('The Catcher in the Rye', 'J.D. Salinger', 1951, 'A coming-of-age story narrated by the iconic Holden Caulfield over a few days in New York City.'),
        ('One Hundred Years of Solitude', 'Gabriel García Márquez', 1967, 'An epic novel that tells the story of the Buendía family across seven generations in the fictional town of Macondo.'),
        ('Brave New World', 'Aldous Huxley', 1932, 'A dystopian novel set in a futuristic World State inhabited by genetically modified citizens.'),
        ('The Grapes of Wrath', 'John Steinbeck', 1939, 'The story of the Joads, a poor family from Oklahoma, displaced from their farmland during the Great Depression.'),
        ('Moby-Dick', 'Herman Melville', 1851, 'The saga of Captain Ahab and his obsessive quest to kill Moby Dick, the white sperm whale.'),
        ('The Road', 'Cormac McCarthy', 2006, 'A post-apocalyptic tale of a father and son walking through burned America toward the sea.'),
        ('Anna Karenina', 'Leo Tolstoy', 1878, 'A complex novel about Russian society at the time, following the affair of married socialite Anna Karenina.'),
        ('Ulysses', 'James Joyce', 1922, 'A modernist novel that follows Leopold Bloom through Dublin over the course of a single day.'),
        ('Crime and Punishment', 'Fyodor Dostoevsky', 1866, 'The mental anguish and moral dilemmas of Raskolnikov, an impoverished ex-student in Saint Petersburg.'),
        ('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880, 'A passionate philosophical novel that enters deeply into the ethical debates of God, free will and morality.'),
        ('Wuthering Heights', 'Emily Brontë', 1847, 'A tale of passionate and all-consuming love set on the Yorkshire moors, centering on Heathcliff and Catherine.'),
        ('Jane Eyre', 'Charlotte Brontë', 1847, 'The story of Jane Eyre, an orphan who becomes a governess and falls in love with the brooding Mr. Rochester.'),
        ('The Picture of Dorian Gray', 'Oscar Wilde', 1890, 'A philosophical novel about a young man who remains forever young while his portrait ages.'),
        ('Middlemarch', 'George Eliot', 1871, 'A study of provincial life in fictional English Midlands town Middlemarch, exploring marriage, religion and politics.'),
        ('Don Quixote', 'Miguel de Cervantes', 1605, 'The story of a man who reads so many chivalric romances that he loses his sanity and decides to become a knight-errant.'),
        ('The Sun Also Rises', 'Ernest Hemingway', 1926, 'An expatriate community of Americans and British living in Paris in the 1920s and travelling to Pamplona.'),
        ('Of Mice and Men', 'John Steinbeck', 1937, 'A novella set during the Great Depression about migrant ranch workers George Milton and Lennie Small.'),
        ('Beloved', 'Toni Morrison', 1987, 'A story inspired by the life of an enslaved African-American woman who, after escaping slavery, kills her own daughter.'),
        ('Invisible Man', 'Ralph Ellison', 1952, 'A story narrated by an unnamed African-American man who considers himself socially invisible.'),
        ('Their Eyes Were Watching God', 'Zora Neale Hurston', 1937, 'A 1937 novel that centers on Janie Crawford in the Florida Everglades.'),
        ('The Age of Innocence', 'Edith Wharton', 1920, 'A story set in upper-class New York City in the 1870s, examining the restrictions and hypocrisies of the Gilded Age.'),
        ('Giovanni\'s Room', 'James Baldwin', 1956, 'A story of love and loss set in 1950s Paris, exploring themes of sexuality and identity.'),
        ('Catch-22', 'Joseph Heller', 1961, 'A satirical war novel set during World War II and is frequently cited as one of the greatest literary works of the twentieth century.'),
        ('The Old Man and the Sea', 'Ernest Hemingway', 1952, 'A short novel about an aging Cuban fisherman who struggles with a giant marlin far out in the Gulf Stream.'),
        ('Lord of the Flies', 'William Golding', 1954, 'A novel about a group of British boys stuck on an uninhabited island who try to govern themselves with disastrous results.'),
        ('A Farewell to Arms', 'Ernest Hemingway', 1929, 'A novel set during the Italian campaign of the First World War, centering on an American ambulance driver.'),
    ],
    'Science Fiction': [
        ('Dune', 'Frank Herbert', 1965, 'An epic science fiction novel set in the distant future amidst a feudal interstellar society where desert planet Arrakis is the only source of a precious resource.'),
        ('Foundation', 'Isaac Asimov', 1951, 'The story of the decline of the Galactic Empire and the efforts of mathematician Hari Seldon to preserve knowledge.'),
        ('Neuromancer', 'William Gibson', 1984, 'A cyberpunk novel following a washed-up computer hacker hired for one last job, which brings him face to face with an AI.'),
        ('The Left Hand of Darkness', 'Ursula K. Le Guin', 1969, 'A science fiction novel set on the planet Gethen, whose inhabitants have no fixed biological gender.'),
        ('Ender\'s Game', 'Orson Scott Card', 1985, 'A military science fiction novel about a young boy, Andrew Ender Wiggin, who is recruited to attend a space military school.'),
        ('The Hitchhiker\'s Guide to the Galaxy', 'Douglas Adams', 1979, 'A comedic science fiction series following Arthur Dent, who escapes the destruction of Earth with an alien friend.'),
        ('Do Androids Dream of Electric Sheep?', 'Philip K. Dick', 1968, 'A post-apocalyptic science fiction novel in which Earth has been devastated by nuclear war.'),
        ('Slaughterhouse-Five', 'Kurt Vonnegut', 1969, 'An anti-war novel centered on the World War II experiences of Billy Pilgrim, who has become unstuck in time.'),
        ('The Martian Chronicles', 'Ray Bradbury', 1950, 'A collection of short stories about the colonization of Mars and the destruction of Martian civilization.'),
        ('Fahrenheit 451', 'Ray Bradbury', 1953, 'A dystopian novel set in the future where books are outlawed and "firemen" burn any that are found.'),
        ('The War of the Worlds', 'H.G. Wells', 1898, 'A science fiction novel describing the Martian invasion of Earth and humanity\'s struggle to survive.'),
        ('I, Robot', 'Isaac Asimov', 1950, 'A collection of short stories about robots and their impact on humanity, introducing the Three Laws of Robotics.'),
        ('The Time Machine', 'H.G. Wells', 1895, 'A science fiction novel about a Victorian-era scientist who builds a machine that allows him to travel through time.'),
        ('Childhood\'s End', 'Arthur C. Clarke', 1953, 'A novel about the peaceful alien invasion of Earth by the mysterious Overlords.'),
        ('A Wrinkle in Time', 'Madeleine L\'Engle', 1962, 'A novel that follows Meg Murry, her brother Charles Wallace, and their friend Calvin O\'Keefe on an interplanetary journey.'),
        ('The Stars My Destination', 'Alfred Bester', 1956, 'A science fiction novel set in a future where teleportation is common, following Gulliver Foyle\'s quest for revenge.'),
        ('Rendezvous with Rama', 'Arthur C. Clarke', 1973, 'A novel about the discovery of a cylindrical alien space vessel that enters the Solar System.'),
        ('The Dispossessed', 'Ursula K. Le Guin', 1974, 'A novel about an anarchist physicist from a moon colony who travels to the planet his people originally abandoned.'),
        ('Hyperion', 'Dan Simmons', 1989, 'A science fiction novel in which seven pilgrims make a journey to the Time Tombs of Hyperion, sharing their stories along the way.'),
        ('Flowers for Algernon', 'Daniel Keyes', 1966, 'A story about Charlie Gordon, a man with low intelligence who undergoes an experimental surgical technique to increase his intelligence.'),
        ('The Andromeda Strain', 'Michael Crichton', 1969, 'A techno-thriller novel about a team of scientists who investigate the outbreak of a deadly extraterrestrial microorganism.'),
        ('Contact', 'Carl Sagan', 1985, 'A novel about the first confirmed extraterrestrial contact and the spiritual and political crises it creates.'),
        ('Snow Crash', 'Neal Stephenson', 1992, 'A cyberpunk novel that explores the near-future of America through the eyes of Hiro Protagonist, a hacker and pizza delivery man.'),
        ('Old Man\'s War', 'John Scalzi', 2005, 'A military science fiction novel about an old man who joins the Colonial Defense Forces to fight against alien species.'),
        ('The Moon is a Harsh Mistress', 'Robert A. Heinlein', 1966, 'A novel about a lunar colony\'s revolt against its Earth-based rulers.'),
        ('Solaris', 'Stanisław Lem', 1961, 'A novel about scientists struggling to communicate with an alien intelligence on the ocean planet Solaris.'),
        ('The Forever War', 'Joe Haldeman', 1974, 'A military science fiction novel depicting a war between humanity and an alien civilization called the Taurans.'),
        ('Annihilation', 'Jeff VanderMeer', 2014, 'A novel about a group of scientists sent to investigate a mysterious, isolated region of coastline known as Area X.'),
        ('All Systems Red', 'Martha Wells', 2017, 'A science fiction novel about a self-described introvert robot that prefers watching TV to socializing.'),
        ('Project Hail Mary', 'Andy Weir', 2021, 'A science fiction novel about a lone astronaut who must save Earth from astronomical disaster.'),
    ],
    'Fantasy': [
        ('The Lord of the Rings', 'J.R.R. Tolkien', 1954, 'An epic high-fantasy novel set in Middle-earth, following the Fellowship\'s quest to destroy the One Ring.'),
        ('Harry Potter and the Philosopher\'s Stone', 'J.K. Rowling', 1997, 'The first book in a series about a young boy who discovers he is a wizard on his eleventh birthday.'),
        ('The Name of the Wind', 'Patrick Rothfuss', 2007, 'A fantasy novel about the childhood and life of the magically gifted young man Kvothe.'),
        ('American Gods', 'Neil Gaiman', 2001, 'A novel about a recently released convict who gets caught in a conflict between old gods brought to America by immigrants and new American gods.'),
        ('The Way of Kings', 'Brandon Sanderson', 2010, 'An epic fantasy novel and the first of ten books planned in the Stormlight Archive series.'),
        ('A Game of Thrones', 'George R.R. Martin', 1996, 'A fantasy novel set in the fictional continents of Westeros and Essos, beginning with the Iron Throne power struggle.'),
        ('Good Omens', 'Terry Pratchett & Neil Gaiman', 1990, 'A humorous fantasy novel about the coming of the Antichrist and the possible end of the world.'),
        ('The Hobbit', 'J.R.R. Tolkien', 1937, 'A children\'s fantasy novel about the quest of home-loving hobbit Bilbo Baggins to win a share of the treasure guarded by Smaug.'),
        ('Mistborn: The Final Empire', 'Brandon Sanderson', 2006, 'A fantasy novel set in a world of ash and mist, where a group of rebels plan to overthrow a seemingly divine ruler.'),
        ('The Lies of Locke Lamora', 'Scott Lynch', 2006, 'A fantasy heist novel set in a fantasy equivalent of Renaissance Venice, following a group of con artists.'),
        ('Jonathan Strange & Mr Norrell', 'Susanna Clarke', 2004, 'A novel about the return of magic to England during the Napoleonic Wars.'),
        ('Uprooted', 'Naomi Novik', 2015, 'A fantasy novel inspired by Polish folklore about a wizard and a young woman from a village near a corrupted forest.'),
        ('The Night Circus', 'Erin Morgenstern', 2011, 'A fantasy novel about a competition between two young magicians at a mysterious magical circus.'),
        ('Spinning Silver', 'Naomi Novik', 2018, 'A fairy tale retelling of Rumpelstiltskin set in a fantasy world inspired by Eastern European folklore.'),
        ('The Bone Witch', 'Rin Chupeco', 2017, 'A fantasy novel about a young girl who accidentally raises her brother from the dead, marking her as a bone witch.'),
        ('Circe', 'Madeline Miller', 2018, 'A novel retelling the story of the legendary sorceress Circe from Greek mythology.'),
        ('The Song of Achilles', 'Madeline Miller', 2011, 'A novel retelling the story of Achilles and his companion Patroclus during the events of the Trojan War.'),
        ('A Wizard\'s Guide to Defensive Baking', 'T. Kingfisher', 2020, 'A fantasy novel about a 14-year-old girl with the power to make gingerbread men come to life.'),
        ('The House in the Cerulean Sea', 'TJ Klune', 2020, 'A fantasy romance novel about a caseworker who is sent to investigate a mysterious orphanage.'),
        ('Piranesi', 'Susanna Clarke', 2020, 'A mystery novel set in a surreal alternate world consisting of an endless labyrinthine house.'),
        ('The Magicians', 'Lev Grossman', 2009, 'A novel about a young man who discovers that the magical world of his favorite childhood books actually exists.'),
        ('Throne of Glass', 'Sarah J. Maas', 2012, 'A fantasy novel about a young assassin who becomes a competitor in a contest to serve as the king\'s champion.'),
        ('The Priory of the Orange Tree', 'Samantha Shannon', 2019, 'An epic standalone fantasy novel about a world on the brink of conflict with a great evil.'),
        ('Six of Crows', 'Leigh Bardugo', 2015, 'A heist fantasy novel about a dangerous crew hired to pull off an impossible heist.'),
        ('The Blade Itself', 'Joe Abercrombie', 2006, 'A dark fantasy novel following several characters in a world of brutal conflict.'),
        ('Elantris', 'Brandon Sanderson', 2005, 'A fantasy novel about a city of fallen gods where the power of the gods has been corrupted.'),
        ('The Eye of the World', 'Robert Jordan', 1990, 'The first novel in the Wheel of Time series, following a group of young people on a quest to save the world.'),
        ('Gardens of the Moon', 'Steven Erikson', 1999, 'An epic fantasy novel and the first book in the Malazan Book of the Fallen series.'),
        ('The Fifth Season', 'N.K. Jemisin', 2015, 'A science fantasy novel set in a world of catastrophic seasons and underground civilizations.'),
        ('Assassin\'s Apprentice', 'Robin Hobb', 1995, 'A fantasy novel about a young boy who is the illegitimate son of the prince and is trained as a royal assassin.'),
    ],
    'Mystery & Thriller': [
        ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 2005, 'A psychological thriller following journalist Mikael Blomkvist and hacker Lisbeth Salander in a murder investigation.'),
        ('Gone Girl', 'Gillian Flynn', 2012, 'A psychological thriller told from two unreliable perspectives about a missing woman and her husband.'),
        ('The Da Vinci Code', 'Dan Brown', 2003, 'A mystery thriller following Robert Langdon who must solve a series of puzzles hidden in Da Vinci\'s artworks.'),
        ('Big Little Lies', 'Liane Moriarty', 2014, 'A mystery novel about three women whose seemingly perfect lives unravel to the point of murder.'),
        ('In the Woods', 'Tana French', 2007, 'A psychological thriller about a detective investigating a murder who discovers links to his own traumatic childhood.'),
        ('The Thursday Murder Club', 'Richard Osman', 2020, 'A mystery novel about four retirees in a retirement village who meet weekly to investigate cold cases.'),
        ('Where the Crawdads Sing', 'Delia Owens', 2018, 'A mystery novel about a young girl who raised herself in the North Carolina marshes and is suspected of murder.'),
        ('And Then There Were None', 'Agatha Christie', 1939, 'A mystery novel about ten strangers who are lured to a remote island and die one by one.'),
        ('The Mysterious Affair at Styles', 'Agatha Christie', 1920, 'The first Hercule Poirot mystery, where Poirot investigates the poisoning of a wealthy woman at her country house.'),
        ('Rebecca', 'Daphne du Maurier', 1938, 'A gothic novel about an unnamed woman who becomes the wife of a widower and is haunted by the memory of his first wife.'),
        ('The Name of the Rose', 'Umberto Eco', 1980, 'A historical mystery novel set in a 14th-century Italian monastery where a monk investigates a series of murders.'),
        ('Silence of the Lambs', 'Thomas Harris', 1988, 'A thriller novel about FBI trainee Clarice Starling who seeks the help of serial killer Hannibal Lecter to catch another serial killer.'),
        ('The Maltese Falcon', 'Dashiell Hammett', 1930, 'A hardboiled detective novel following Sam Spade as he investigates the murder of his partner.'),
        ('The Big Sleep', 'Raymond Chandler', 1939, 'A hardboiled detective novel featuring the iconic Philip Marlowe investigating a case of blackmail.'),
        ('In Cold Blood', 'Truman Capote', 1966, 'A non-fiction crime novel about the murder of a Kansas family and the investigation that followed.'),
        ('Gone Girl', 'Gillian Flynn', 2012, 'A psychological thriller about a woman who goes missing on her fifth wedding anniversary.'),
        ('The Girl on the Train', 'Paula Hawkins', 2015, 'A psychological thriller about a divorcee who becomes entangled in a missing persons investigation.'),
        ('Sharp Objects', 'Gillian Flynn', 2006, 'A psychological thriller about a journalist who returns to her hometown to cover the murders of two young girls.'),
        ('The Woman in White', 'Wilkie Collins', 1859, 'A Victorian mystery novel involving a mysterious woman in white and a complex conspiracy of identity theft.'),
        ('The Hound of the Baskervilles', 'Arthur Conan Doyle', 1902, 'A Sherlock Holmes novel about a supernatural hound that haunts the Baskerville family.'),
        ('Murder on the Orient Express', 'Agatha Christie', 1934, 'A Hercule Poirot novel set on the Orient Express where a passenger is found murdered.'),
        ('Death on the Nile', 'Agatha Christie', 1937, 'A Hercule Poirot novel where Poirot investigates the murder of a young heiress on a Nile steamer.'),
        ('The Seven Deaths of Evelyn Hardcastle', 'Stuart Turton', 2018, 'A mystery novel in which the same day repeats itself and the protagonist must identify the murderer.'),
        ('Verity', 'Colleen Hoover', 2018, 'A psychological thriller about a struggling author who discovers disturbing information about the bestselling author she is helping.'),
        ('The Last House on Needles Lane', 'Steph Broadribb', 2022, 'A thriller about a couple who move to a new neighborhood only to discover dark secrets.'),
        ('The Sanatorium', 'Sarah Pearse', 2021, 'A thriller set in a remote Swiss sanatorium where guests start disappearing.'),
        ('The Silent Patient', 'Alex Michaelides', 2019, 'A psychological thriller about a famous painter who refuses to speak after allegedly murdering her husband.'),
        ('Behind Closed Doors', 'B.A. Paris', 2016, 'A psychological thriller about a seemingly perfect marriage that hides dark secrets.'),
        ('The Woman in the Window', 'A.J. Finn', 2018, 'A psychological thriller about an agoraphobic woman who witnesses a crime from her window.'),
        ('Finlay Donovan is Killing It', 'Elle Cosimano', 2021, 'A comedic thriller about a struggling crime novelist who is mistaken for a contract killer.'),
    ],
    'Biography': [
        ('The Diary of a Young Girl', 'Anne Frank', 1947, 'The diary of Jewish teenager Anne Frank while she was in hiding with her family during the Nazi occupation.'),
        ('Long Walk to Freedom', 'Nelson Mandela', 1994, 'The autobiography of Nelson Mandela, recounting his childhood, his time in prison, and his presidency.'),
        ('The Story of My Experiments with Truth', 'Mahatma Gandhi', 1927, 'Gandhi\'s autobiography covering his life from childhood through to 1921 and the development of his philosophy.'),
        ('Steve Jobs', 'Walter Isaacson', 2011, 'The biography of Apple co-founder Steve Jobs, based on more than forty interviews with Jobs himself.'),
        ('Becoming', 'Michelle Obama', 2018, 'The memoir of former U.S. first lady Michelle Obama, covering her childhood to life after the White House.'),
        ('The Autobiography of Benjamin Franklin', 'Benjamin Franklin', 1791, 'Franklin\'s unfinished autobiography describing his early life and the values that guided him.'),
        ('I Know Why the Caged Bird Sings', 'Maya Angelou', 1969, 'The first of seven autobiographies by Maya Angelou, describing her life up to the age of 17.'),
        ('My Experiments with Truth', 'Mahatma Gandhi', 1929, 'Gandhi\'s account of his life and the development of his philosophy of nonviolent resistance.'),
        ('The Glass Castle', 'Jeannette Walls', 2005, 'A memoir about a young girl growing up with eccentric, nomadic parents who prioritize creativity over stability.'),
        ('When Breath Becomes Air', 'Paul Kalanithi', 2016, 'A memoir by a neurosurgeon diagnosed with terminal lung cancer as he faced his own mortality.'),
        ('Born a Crime', 'Trevor Noah', 2016, 'The memoir of Trevor Noah, the host of The Daily Show, about growing up in apartheid South Africa.'),
        ('Educated', 'Tara Westover', 2018, 'A memoir about a woman who grew up in a survivalist family in rural Idaho and educated herself.'),
        ('Wild', 'Cheryl Strayed', 2012, 'A memoir about the author\'s solo hike along the Pacific Crest Trail to heal after a period of personal troubles.'),
        ('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 2010, 'The biography of Henrietta Lacks, a Black woman whose cancer cells became the first immortal human cell line.'),
        ('Into the Wild', 'Jon Krakauer', 1996, 'The story of Christopher McCandless, a young man who abandoned civilization to live in the Alaskan wilderness.'),
        ('Night', 'Elie Wiesel', 1960, 'A memoir about Elie Wiesel\'s experiences as a prisoner in Nazi concentration camps during the Holocaust.'),
        ('The Color of Water', 'James McBride', 1996, 'A memoir about the author\'s white Jewish mother and how she raised twelve children with little money.'),
        ('Just Kids', 'Patti Smith', 2010, 'A memoir about Patti Smith\'s early life in New York City and her friendship with Robert Mapplethorpe.'),
        ('The Year of Magical Thinking', 'Joan Didion', 2005, 'A memoir about grief, written in the year following the death of Joan Didion\'s husband and daughter.'),
        ('Hillbilly Elegy', 'J.D. Vance', 2016, 'A memoir about the author\'s upbringing in Appalachian Ohio and the struggles facing working-class white Americans.'),
        ('A Beautiful Mind', 'Sylvia Nasar', 1998, 'The biography of mathematician John Nash, who struggled with paranoid schizophrenia while making groundbreaking contributions to game theory.'),
        ('The Innovators', 'Walter Isaacson', 2014, 'The story of the visionaries and hackers who created the digital revolution.'),
        ('Leonardo da Vinci', 'Walter Isaacson', 2017, 'A biography of the ultimate Renaissance man, Leonardo da Vinci, exploring his creativity and curiosity.'),
        ('Churchill: Walking with Destiny', 'Andrew Roberts', 2018, 'A comprehensive biography of Winston Churchill, regarded as one of the greatest leaders of the 20th century.'),
        ('Alexander Hamilton', 'Ron Chernow', 2004, 'A comprehensive biography of Alexander Hamilton, one of America\'s founding fathers.'),
        ('Grant', 'Ron Chernow', 2017, 'A biography of Ulysses S. Grant, covering his military career and presidency.'),
        ('The Rise of Theodore Roosevelt', 'Edmund Morris', 1979, 'The first volume of a trilogy about Theodore Roosevelt\'s life up to his presidency.'),
        ('Eleanor Roosevelt: A Life of Discovery', 'Russell Freedman', 1993, 'A biography of Eleanor Roosevelt, one of the most influential women of the 20th century.'),
        ('Unbroken', 'Laura Hillenbrand', 2010, 'The story of Louis Zamperini, a World War II prisoner of war who survived extraordinary hardship.'),
        ('The Wright Brothers', 'David McCullough', 2015, 'The story of Orville and Wilbur Wright and their determination to achieve powered flight.'),
    ],
    'History': [
        ('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 2011, 'A wide-ranging overview of the history of Homo sapiens from the Stone Age to the 21st century.'),
        ('Guns, Germs, and Steel', 'Jared Diamond', 1997, 'A geographical and anthropological look at why some civilizations came to dominate others.'),
        ('The Silk Roads', 'Peter Frankopan', 2015, 'A new history of the world, centering on the Silk Roads—the network of routes linking East and West.'),
        ('SPQR: A History of Ancient Rome', 'Mary Beard', 2015, 'An exploration of ancient Rome, from its origins to the later stages of its empire.'),
        ('The History of the Peloponnesian War', 'Thucydides', -431, 'An ancient Greek account of the war between the Peloponnesian League and the Athenian Empire.'),
        ('The Rise and Fall of the Third Reich', 'William L. Shirer', 1960, 'A comprehensive history of Nazi Germany from its founding to its defeat in World War II.'),
        ('The Guns of August', 'Barbara Tuchman', 1962, 'An account of the first month of World War I, exploring how the conflict started.'),
        ('A People\'s History of the United States', 'Howard Zinn', 1980, 'A history of the United States from the perspective of ordinary people, rather than political leaders.'),
        ('The Diary of a Young Girl', 'Anne Frank', 1947, 'The wartime diary of Anne Frank, a Jewish girl hiding from the Nazis in Amsterdam.'),
        ('Band of Brothers', 'Stephen Ambrose', 1992, 'The story of Easy Company, 506th Regiment of the 101st Airborne Division from training through World War II.'),
        ('The Civil War', 'Shelby Foote', 1958, 'A comprehensive narrative history of the American Civil War in three volumes.'),
        ('1776', 'David McCullough', 2005, 'The story of the turbulent year of 1776 and the battles that defined the course of the American Revolution.'),
        ('Team of Rivals', 'Doris Kearns Goodwin', 2005, 'A biographical account of Abraham Lincoln and the powerful men who became his rivals before forming his cabinet.'),
        ('The Warmth of Other Suns', 'Isabel Wilkerson', 2010, 'A chronicle of the Great Migration, in which six million African Americans fled the South for northern and western cities.'),
        ('The Splendid and the Vile', 'Erik Larson', 2020, 'A story about Winston Churchill and his family during the Blitz in World War II.'),
        ('Dead Wake', 'Erik Larson', 2015, 'The story of the last voyage of the Lusitania and its sinking by a German U-boat in 1915.'),
        ('The Devil in the White City', 'Erik Larson', 2003, 'A narrative account of the 1893 World\'s Columbian Exposition in Chicago and a serial killer who operated there.'),
        ('Killers of the Flower Moon', 'David Grann', 2017, 'The story of the Osage Indian murders in the 1920s and the founding of the FBI.'),
        ('The Sixth Extinction', 'Elizabeth Kolbert', 2014, 'An account of the ongoing mass extinction event and its causes, focusing on human activity.'),
        ('The Fate of Rome', 'Kyle Harper', 2017, 'An examination of how climate change and pandemic disease contributed to the fall of the Roman Empire.'),
        ('Lost in Shangri-La', 'Mitchell Zuckoff', 2011, 'The story of an American military plane crash in New Guinea during World War II.'),
        ('Empire of the Summer Moon', 'S.C. Gwynne', 2010, 'The story of the Comanche people and the decades-long war between the Comanches and the Texas Rangers.'),
        ('The Wright Brothers', 'David McCullough', 2015, 'The story of Orville and Wilbur Wright and their determination to invent the airplane.'),
        ('John Adams', 'David McCullough', 2001, 'A biography of the second President of the United States, John Adams.'),
        ('The Innovators', 'Walter Isaacson', 2014, 'A history of the digital revolution and the visionaries who created it.'),
        ('Alexander the Great', 'Philip Freeman', 2011, 'A concise biography of one of the greatest military commanders in history.'),
        ('Caesar: Life of a Colossus', 'Adrian Goldsworthy', 2006, 'A comprehensive biography of Julius Caesar, the Roman general and statesman.'),
        ('Napoleon: A Life', 'Andrew Roberts', 2014, 'A biography of Napoleon Bonaparte based on new research including Napoleon\'s letters.'),
        ('The Romanovs', 'Simon Sebag Montefiore', 2016, 'A history of the Romanov dynasty that ruled Russia for three centuries.'),
        ('The Plantagenets', 'Dan Jones', 2012, 'A history of the Plantagenet dynasty that ruled England from 1154 to 1399.'),
    ],
    'Science': [
        ('A Brief History of Time', 'Stephen Hawking', 1988, 'A popular-science book about cosmology, exploring topics such as the Big Bang, black holes and the nature of time.'),
        ('The Selfish Gene', 'Richard Dawkins', 1976, 'A book about evolutionary biology that introduced the concept of the selfish gene and coined the term "meme".'),
        ('The Double Helix', 'James D. Watson', 1968, 'A personal account of the discovery of the DNA double helix by Nobel Prize winner James Watson.'),
        ('Cosmos', 'Carl Sagan', 1980, 'A popular science book accompanying Carl Sagan\'s television series of the same name, exploring the universe.'),
        ('The Origin of Species', 'Charles Darwin', 1859, 'Darwin\'s landmark work explaining the theory of evolution through natural selection.'),
        ('The Elegant Universe', 'Brian Greene', 1999, 'An exploration of superstring theory and the quest for a unified theory of everything.'),
        ('The Gene', 'Siddhartha Mukherjee', 2016, 'An intimate history of the gene, exploring its discovery and the ongoing revolution in genetic research.'),
        ('Being Mortal', 'Atul Gawande', 2014, 'A book about aging, end-of-life care, and how medicine can improve the quality of life for aging patients.'),
        ('The Emperor of All Maladies', 'Siddhartha Mukherjee', 2010, 'A biography of cancer, tracing the disease from its first mentions in ancient Egypt to the present.'),
        ('The Innovators', 'Walter Isaacson', 2014, 'The story of the creative leaps behind the computer and internet revolution.'),
        ('Pale Blue Dot', 'Carl Sagan', 1994, 'A vision of the human future in space, exploring what it means for humanity to be citizens of the cosmos.'),
        ('The Character of Physical Law', 'Richard Feynman', 1965, 'A series of lectures by Richard Feynman about the nature of the laws of physics.'),
        ('QED: The Strange Theory of Light and Matter', 'Richard Feynman', 1985, 'A popular science book about quantum electrodynamics, based on lectures given by Feynman.'),
        ('The Pleasure of Finding Things Out', 'Richard Feynman', 1999, 'A collection of Feynman\'s shorter works exploring the joy of discovery in science.'),
        ('The Fabric of the Cosmos', 'Brian Greene', 2004, 'An exploration of space, time, and the texture of reality by the author of The Elegant Universe.'),
        ('Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', 2017, 'A primer on modern astrophysics for those who want the broad strokes of the universe quickly.'),
        ('The Quantum World', 'Kenneth W. Ford', 2004, 'An introduction to quantum mechanics for those without a background in physics.'),
        ('A Short History of Nearly Everything', 'Bill Bryson', 2003, 'An overview of scientific understanding of the universe, from the Big Bang to the rise of civilization.'),
        ('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 2010, 'The story of Henrietta Lacks and the HeLa cells that revolutionized medicine.'),
        ('The Body: A Guide for Occupants', 'Bill Bryson', 2019, 'A tour of the human body and its extraordinary workings.'),
        ('The Code Breaker', 'Walter Isaacson', 2021, 'The story of Jennifer Doudna, CRISPR, and the future of the human race.'),
        ('Entangled Life', 'Merlin Sheldrake', 2020, 'An exploration of the fascinating world of fungi and how they shape our world.'),
        ('The Hidden Life of Trees', 'Peter Wohlleben', 2015, 'A forester\'s account of the surprising social lives of trees and how they communicate.'),
        ('Why We Sleep', 'Matthew Walker', 2017, 'An exploration of the science of sleep and its importance for our health and well-being.'),
        ('The Circadian Code', 'Satchin Panda', 2019, 'A guide to using our internal clock to protect our health and prevent disease.'),
        ('Behave', 'Robert Sapolsky', 2017, 'An exploration of the biology of human behavior, from neuroscience to evolution to culture.'),
        ('The Creative Destruction of Medicine', 'Eric Topol', 2012, 'How the digital revolution can create better health care.'),
        ('Genome', 'Matt Ridley', 1999, 'A tour of the human genome, using one gene from each of our 23 pairs of chromosomes.'),
        ('The Language of God', 'Francis Collins', 2006, 'A scientist presents evidence for belief in God and the compatibility of faith and science.'),
        ('Lab Girl', 'Hope Jahren', 2016, 'A memoir by a scientist about her life and her deep connection to the natural world.'),
    ],
    'Technology': [
        ('The Lean Startup', 'Eric Ries', 2011, 'A methodology for building startups and developing businesses through validated learning and iterative development.'),
        ('Zero to One', 'Peter Thiel', 2014, 'Notes on startups and how to build companies that create new things.'),
        ('The Innovators', 'Walter Isaacson', 2014, 'A history of the digital revolution and the visionaries who created the computer and the internet.'),
        ('Thinking, Fast and Slow', 'Daniel Kahneman', 2011, 'A summary of research by Nobel laureate Daniel Kahneman on the two systems of thought that drive human decisions.'),
        ('Clean Code', 'Robert C. Martin', 2008, 'A handbook of agile software craftsmanship that shows how to write code that is clean and maintainable.'),
        ('The Pragmatic Programmer', 'David Thomas & Andrew Hunt', 1999, 'A collection of tips and tricks for software developers on how to be better programmers.'),
        ('Design Patterns', 'Gang of Four', 1994, 'A catalogue of reusable solutions to commonly occurring design problems in software engineering.'),
        ('Code: The Hidden Language of Computer Hardware and Software', 'Charles Petzold', 1999, 'An exploration of how computers work from the binary code level up.'),
        ('The Mythical Man-Month', 'Fred Brooks', 1975, 'Essays on software engineering and project management, based on Brooks\'s experience at IBM.'),
        ('Refactoring', 'Martin Fowler', 1999, 'A guide to improving the design of existing code through a catalog of refactoring techniques.'),
        ('Introduction to Algorithms', 'Thomas Cormen et al.', 1990, 'A comprehensive textbook covering many aspects of algorithms and data structures.'),
        ('The Art of Computer Programming', 'Donald Knuth', 1968, 'A comprehensive monograph on the analysis and design of computer algorithms.'),
        ('Gödel, Escher, Bach', 'Douglas Hofstadter', 1979, 'A metaphorical exploration of cognition, consciousness and artificial intelligence through a strange loop concept.'),
        ('The Computer Boys Take Over', 'Nathan Ensmenger', 2010, 'A history of how a group of eccentric technologists unwittingly shaped the development of computing.'),
        ('Hackers: Heroes of the Computer Revolution', 'Steven Levy', 1984, 'A history of the early computer hobbyists and programmers who created the computer revolution.'),
        ('The New Turing Omnibus', 'Alexander Dewdney', 1993, 'Sixty-six excursions in computer science covering everything from neural networks to algorithms.'),
        ('Structure and Interpretation of Computer Programs', 'Harold Abelson', 1996, 'A classic textbook on computer programming using the Scheme programming language.'),
        ('Working Effectively with Legacy Code', 'Michael Feathers', 2004, 'Strategies for dealing with and changing large, poorly-documented systems.'),
        ('Domain-Driven Design', 'Eric Evans', 2003, 'A methodology for developing complex software systems that are driven by domain models.'),
        ('Building Microservices', 'Sam Newman', 2015, 'A guide to designing, building and deploying microservices-based distributed systems.'),
        ('Continuous Delivery', 'Jez Humble & David Farley', 2010, 'A book on software engineering that teaches how to release software reliably and quickly.'),
        ('The Phoenix Project', 'Gene Kim et al.', 2013, 'A novel about an IT manager who must rescue a project that is critical to the survival of the company.'),
        ('The DevOps Handbook', 'Gene Kim et al.', 2016, 'How to create world-class agility, reliability and security in technology organizations.'),
        ('Site Reliability Engineering', 'Niall Murphy et al.', 2016, 'How Google runs production systems and the principles behind their approach.'),
        ('Kubernetes in Action', 'Marko Luksa', 2017, 'A practical guide to understanding and deploying containerized applications with Kubernetes.'),
        ('Docker Deep Dive', 'Nigel Poulton', 2016, 'A practical guide to Docker and containerization technology.'),
        ('Python Crash Course', 'Eric Matthes', 2015, 'A hands-on, project-based introduction to programming with Python.'),
        ('JavaScript: The Good Parts', 'Douglas Crockford', 2008, 'A guide to the best features of JavaScript that makes the language great.'),
        ('Eloquent JavaScript', 'Marijn Haverbeke', 2011, 'A modern introduction to programming using JavaScript.'),
        ('You Don\'t Know JS', 'Kyle Simpson', 2014, 'A deep dive into the core mechanisms of the JavaScript language.'),
    ],
    'Romance': [
        ('Outlander', 'Diana Gabaldon', 1991, 'A historical romance about a 20th-century British nurse who travels back in time to 18th-century Scotland.'),
        ('The Notebook', 'Nicholas Sparks', 1996, 'A story of enduring love between Noah Calhoun and Allie Hamilton, told through Noah\'s diary.'),
        ('Me Before You', 'Jojo Moyes', 2012, 'A romantic novel about a young woman who becomes a caregiver for a quadriplegic man and falls in love.'),
        ('The Hating Game', 'Sally Thorne', 2016, 'A romantic comedy about two executive assistants who are rivals until they realize their feelings.'),
        ('It Ends with Us', 'Colleen Hoover', 2016, 'A romance novel that deals with difficult topics including abuse and self-discovery.'),
        ('The Kiss Quotient', 'Helen Hoang', 2018, 'A romance novel about an econometrician with autism who hires a male escort to help her with relationships.'),
        ('People We Meet on Vacation', 'Emily Henry', 2021, 'A romance novel about two best friends who take annual vacations together and their evolving relationship.'),
        ('Beach Read', 'Emily Henry', 2020, 'A romance novel about two authors with writer\'s block who challenge each other to write in the other\'s genre.'),
        ('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 2017, 'A novel about a Hollywood icon who reveals her life story and her seven marriages to an unknown journalist.'),
        ('Daisy Jones and The Six', 'Taylor Jenkins Reid', 2019, 'A fictional oral history of a rock band in the 1970s and the creation of their final album.'),
        ('One Last Stop', 'Casey McQuiston', 2021, 'A romance novel about a young woman who falls for a girl who is stuck in time on the subway.'),
        ('Red, White & Royal Blue', 'Casey McQuiston', 2019, 'A romance novel about the son of the American president who falls in love with a British prince.'),
        ('The Love Hypothesis', 'Ali Hazelwood', 2021, 'A romance novel about a PhD student who fake-dates a professor to convince her friend she has moved on.'),
        ('Act Your Age, Eve Brown', 'Talia Hibbert', 2021, 'A romance novel about a woman who crashes her car into a man\'s new business and must work for him.'),
        ('Get a Life, Chloe Brown', 'Talia Hibbert', 2019, 'A romance novel about a woman who creates a list of life experiences and falls for her building manager.'),
        ('Tweet Cute', 'Emma Lord', 2021, 'A romance novel about two students who realize a rival on social media is also a classmate they are falling for.'),
        ('Written in the Stars', 'Alexandria Bellefleur', 2020, 'A romance novel about two women who begin fake dating to escape awkward situations.'),
        ('Second First Impressions', 'Sally Thorne', 2021, 'A romance novel about an uptight receptionist and a free-spirited man who become roommates.'),
        ('The Spanish Love Deception', 'Elena Armas', 2021, 'A romance novel about a woman who asks a colleague to pretend to be her boyfriend at a wedding.'),
        ('Party of Two', 'Jasmine Guillory', 2020, 'A romance novel about a lawyer who falls for a senator in a bar before knowing who he is.'),
        ('The Deal', 'Elle Kennedy', 2015, 'A romance novel about a girl who asks a popular hockey player to help her get another guy\'s attention.'),
        ('The Score', 'Elle Kennedy', 2016, 'A romance novel about a hockey player known for his playboy ways who falls for a drama student.'),
        ('The Unhoneymooners', 'Christina Lauren', 2019, 'A romance novel about a woman who goes on her twin sister\'s honeymoon after food poisoning strikes.'),
        ('Twice in a Blue Moon', 'Christina Lauren', 2019, 'A romance novel about a woman who reunites with a man who broke her heart ten years earlier.'),
        ('To All the Boys I\'ve Loved Before', 'Jenny Han', 2014, 'A romance novel about a girl whose secret letters to her crushes are accidentally mailed.'),
        ('The Fault in Our Stars', 'John Green', 2012, 'A romance novel about two cancer-stricken teenagers who fall in love at a support group.'),
        ('Eleanor & Park', 'Rainbow Rowell', 2013, 'A romance novel about two misfits who find love on a school bus in 1986.'),
        ('Attachments', 'Rainbow Rowell', 2011, 'A romance novel about a man who monitors employee emails and falls for a woman through her emails.'),
        ('Landline', 'Rainbow Rowell', 2014, 'A romance novel about a comedy writer who discovers a magic phone that lets her call her husband in the past.'),
        ('Normal People', 'Sally Rooney', 2018, 'A novel about the complicated relationship between two Irish students who keep reconnecting over the years.'),
    ],
    'Self-Help': [
        ('Atomic Habits', 'James Clear', 2018, 'A practical guide to building good habits and breaking bad ones using the science of tiny changes.'),
        ('The 7 Habits of Highly Effective People', 'Stephen R. Covey', 1989, 'A business and self-help book presenting an approach to being effective in achieving personal goals.'),
        ('How to Win Friends and Influence People', 'Dale Carnegie', 1936, 'A self-help book that teaches principles for social and interpersonal skills.'),
        ('Think and Grow Rich', 'Napoleon Hill', 1937, 'A personal development and self-improvement book examining the power of personal beliefs.'),
        ('The Power of Now', 'Eckhart Tolle', 1997, 'A guide to spiritual enlightenment focusing on the importance of living in the present moment.'),
        ('Mindset: The New Psychology of Success', 'Carol S. Dweck', 2006, 'A psychologist\'s exploration of the growth mindset and how to cultivate it for success.'),
        ('The Subtle Art of Not Giving a F*ck', 'Mark Manson', 2016, 'A counterintuitive approach to living a good life by focusing on what truly matters.'),
        ('Deep Work', 'Cal Newport', 2016, 'Rules for focused success in a distracted world, arguing for the benefits of deep work.'),
        ('Essentialism', 'Greg McKeown', 2014, 'A disciplined, systematic approach to determining where your highest point of contribution lies.'),
        ('The Four Agreements', 'Don Miguel Ruiz', 1997, 'A book of Toltec wisdom that describes a code of conduct to achieve freedom from suffering.'),
        ('You Are a Badass', 'Jen Sincero', 2013, 'A self-help book that teaches readers how to create a life they love using positive thinking.'),
        ('Girl, Wash Your Face', 'Rachel Hollis', 2018, 'A motivational book that addresses twenty lies women tell themselves that hold them back.'),
        ('Dare to Lead', 'Brené Brown', 2018, 'A book about courageous leadership and how to build braver, more creative organizations.'),
        ('The Gifts of Imperfection', 'Brené Brown', 2010, 'A guide to living a wholehearted life, embracing imperfection and cultivating self-compassion.'),
        ('Daring Greatly', 'Brené Brown', 2012, 'A book about the courage to be vulnerable and how it can transform our lives and relationships.'),
        ('Rising Strong', 'Brené Brown', 2015, 'A book about how to get back up after a fall and use the experience to grow.'),
        ('The Miracle Morning', 'Hal Elrod', 2012, 'A guide to transforming your life through a morning routine of six practices.'),
        ('The 5 AM Club', 'Robin Sharma', 2018, 'A fable about how waking up at 5 AM can transform your health, happiness and productivity.'),
        ('Can\'t Hurt Me', 'David Goggins', 2018, 'A memoir by a Navy SEAL and ultramarathon runner about mastering your mind.'),
        ('The Obstacle is the Way', 'Ryan Holiday', 2014, 'A guide to using obstacles as opportunities for growth, based on Stoic philosophy.'),
        ('Meditations', 'Marcus Aurelius', 180, 'A series of personal writings by the Roman Emperor Marcus Aurelius on Stoic philosophy.'),
        ('Man\'s Search for Meaning', 'Viktor E. Frankl', 1946, 'A psychiatrist\'s account of his experiences in Nazi concentration camps and the lessons learned.'),
        ('The Road to Character', 'David Brooks', 2015, 'A book about the inner journey to becoming a person of character and virtue.'),
        ('Drive: The Surprising Truth About What Motivates Us', 'Daniel H. Pink', 2009, 'An exploration of the science of motivation, arguing against traditional carrot-and-stick approaches.'),
        ('The Art of Happiness', 'Dalai Lama', 1998, 'A guide to finding happiness through training the mind, based on conversations between a psychiatrist and the Dalai Lama.'),
        ('The Power of Positive Thinking', 'Norman Vincent Peale', 1952, 'A self-help book that teaches the power of believing in yourself and the value of positive thinking.'),
        ('Flow: The Psychology of Optimal Experience', 'Mihaly Csikszentmihalyi', 1990, 'An exploration of the concept of flow—a state of optimal experience that leads to happiness.'),
        ('Emotional Intelligence', 'Daniel Goleman', 1995, 'An exploration of why emotional intelligence may matter more than IQ for success.'),
        ('The Artist\'s Way', 'Julia Cameron', 1992, 'A course in discovering and recovering your creative self through a twelve-week program.'),
        ('Big Magic', 'Elizabeth Gilbert', 2015, 'A book about creative living beyond fear, exploring ideas about creativity and inspiration.'),
    ],
}

EVENTS = [
    {
        'title': 'Summer Reading Challenge Kickoff',
        'description': 'Join us for the launch of our annual Summer Reading Challenge! There will be books, prizes, and activities for all ages. Meet your fellow readers and discover new titles to explore this summer.',
        'location': 'Main Hall, City Library',
        'days_from_now': 7,
    },
    {
        'title': 'Author Talk: The Future of Fiction',
        'description': 'Award-winning author Sofia Reyes joins us to discuss her latest novel and the evolving landscape of contemporary fiction. Q&A session to follow.',
        'location': 'Reading Room B, City Library',
        'days_from_now': 14,
    },
    {
        'title': 'Children\'s Story Hour',
        'description': 'A magical morning of storytelling for children aged 3-8. Our librarians will read from beloved classics and new favorites, followed by a craft activity.',
        'location': 'Children\'s Section, City Library',
        'days_from_now': 3,
    },
    {
        'title': 'Book Club: Science Fiction Edition',
        'description': 'This month\'s book club meets to discuss "Project Hail Mary" by Andy Weir. All are welcome — no prior reading required, but the book is available for borrowing at the front desk.',
        'location': 'Community Room, City Library',
        'days_from_now': 21,
    },
    {
        'title': 'Digital Literacy Workshop',
        'description': 'A hands-on workshop covering essential digital skills for seniors — from email and social media to online banking and video calls. Free devices available during the session.',
        'location': 'Computer Lab, City Library',
        'days_from_now': 10,
    },
    {
        'title': 'Local History Exhibit Opening',
        'description': 'We are proud to present "Our City Through the Ages" — a photographic and archival exhibition celebrating 200 years of our city\'s history. Refreshments served.',
        'location': 'Gallery Space, City Library',
        'days_from_now': 18,
    },
    {
        'title': 'Teen Creative Writing Workshop',
        'description': 'A two-hour workshop for teens aged 13-18 led by local poet Marcus Bell. Explore poetry, short fiction and personal essays in a supportive environment.',
        'location': 'Teen Zone, City Library',
        'days_from_now': 28,
    },
    {
        'title': 'Language Learning Meet-Up',
        'description': 'Practice your language skills! This month\'s languages are Spanish and French. Beginners and advanced speakers welcome. Language learning resources provided.',
        'location': 'Study Room 3, City Library',
        'days_from_now': 35,
    },
    {
        'title': 'Film Screening: Adaptations Night',
        'description': 'Watch the film adaptation of "The Name of the Rose" followed by a discussion comparing the book and the movie. Popcorn provided!',
        'location': 'Screening Room, City Library',
        'days_from_now': 45,
    },
    {
        'title': 'Annual Library Gala',
        'description': 'Our biggest celebration of the year! Join us for an evening of reading, music, food and community. Tickets are free but registration is required.',
        'location': 'City Library — All Floors',
        'days_from_now': 60,
    },
]


class Command(BaseCommand):
    help = 'Seed the database with sample books, genres and events'

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Clear existing data before seeding')

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write('Clearing existing data...')
            Book.objects.all().delete()
            Genre.objects.all().delete()
            Event.objects.all().delete()

        self.stdout.write('Seeding genres and books...')
        total_books = 0

        for genre_name, books in GENRES_AND_BOOKS.items():
            genre, _ = Genre.objects.get_or_create(name=genre_name)

            for title, author, year, description in books:
                if Book.objects.filter(title=title, author=author).exists():
                    continue
                total_copies = random.randint(2, 8)
                available = random.randint(0, total_copies)
                borrow_count = random.randint(0, 150)
                if available == 0:
                    book_status = Book.Status.BORROWED
                elif available < total_copies:
                    book_status = Book.Status.RESERVED
                else:
                    book_status = Book.Status.AVAILABLE

                Book.objects.create(
                    title=title,
                    author=author,
                    year=max(year, 1),
                    description=description,
                    genre=genre,
                    status=book_status,
                    total_copies=total_copies,
                    available_copies=available,
                    borrow_count=borrow_count,
                )
                total_books += 1

        self.stdout.write(f'  Created {total_books} books across {len(GENRES_AND_BOOKS)} genres.')

        self.stdout.write('Seeding events...')
        total_events = 0
        now = timezone.now()
        for event_data in EVENTS:
            days = event_data.pop('days_from_now')
            event_date = now + timedelta(days=days)
            obj, created = Event.objects.get_or_create(
                title=event_data['title'],
                defaults={**event_data, 'date': event_date},
            )
            if created:
                total_events += 1

        self.stdout.write(f'  Created {total_events} events.')
        self.stdout.write(self.style.SUCCESS(f'\nDone! Seeded {total_books} books and {total_events} events.'))
